// AUTO-GENERATED by `cargo xtask build` - DO NOT EDIT
// This is a placeholder - run `cargo xtask build` to generate the real manifest

export interface PluginEntry {
  language: string;
  package: string;
  version: string;
  cdn_js: string;
  cdn_wasm: string;
  local_js: string;
  local_wasm: string;
}

export interface PluginsManifest {
  generated_at: string;
  entries: PluginEntry[];
}

export const pluginsManifest: PluginsManifest = {
  generated_at: "placeholder",
  entries: [],
};
