// AUTO-GENERATED by `cargo xtask build` - DO NOT EDIT

export interface PluginEntry {
  language: string;
  package: string;
  version: string;
  cdn_js: string;
  cdn_wasm: string;
  local_js: string;
  local_wasm: string;
}

export interface PluginsManifest {
  generated_at: string;
  entries: PluginEntry[];
}

export const pluginsManifest: PluginsManifest = {
  generated_at: "<%= generated_at %>",
  entries: [
<% for entry in entries { %>
    {
      language: "<%= entry.language %>",
      package: "<%= entry.package %>",
      version: "<%= entry.version %>",
      cdn_js: "<%= entry.cdn_js %>",
      cdn_wasm: "<%= entry.cdn_wasm %>",
      local_js: "<%= entry.local_js %>",
      local_wasm: "<%= entry.local_wasm %>",
    },
<% } %>
  ],
};
